### ISSUE TITLE
Dep Package Version Err

### ISSUE THREAD

**Issue by CyberDudeJ** [MoonlightCapital/discord-py-template#24]
```Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement pkg_resources (from versions: none)
ERROR: No matching distribution found for pkg_resources
```
pip cannot install dependencies, versions mismatched or something

**Comment by MoonlightCapital** [comment]
Thanks for opening an issue! I have slimmed down the requirements.txt file with commit 097ebf0 

I tested my changes in a venv running Python 3.12.2 and pip 24.0 on Ubuntu 24.04. Note that you may need to run `python -m pip install setuptools -U --force-reinstall` if Nextcord errors.

Let me know if this helps!

**Comment by CyberDudeJ** [comment]
:+1:
